language: python
python:
  - 3.6
# command to install dependencies
install:
  - pip install -r requirements.txt
before_script:
  - psql -c "CREATE DATABASE postgres;" -U postgres
  - psql -c "ALTER USER postgres WITH PASSWORD 'postgres';" -U postgres
# command to run tests
script:
  - pytest --cov-report= --cov=app/ tests
#run coverage tests
after_success:
  - coveralls
  - codecov --token=385b5cb4-8b1a-4aaa-8543-18f855d481bd