language: python
python:
  - 3.6
# command to install dependencies
install:
  - pip install -r requirements.txt
# command to run tests
script:
  - pytest --cov-report= --cov=app/ tests
#run coverage tests
after_success:
  - coveralls
  - codecov --token=385b5cb4-8b1a-4aaa-8543-18f855d481bd